CREATE TABLE `artists` (
	`id` text PRIMARY KEY NOT NULL,
	`legacy_id` text NOT NULL,
	`slug` text NOT NULL,
	`name` text NOT NULL,
	`category` text,
	`one_liner` text,
	`bio` text,
	`template_type` text DEFAULT '콜라주형',
	`portfolio_links` text DEFAULT '[]' NOT NULL,
	`youtube_videos` text DEFAULT '[]' NOT NULL,
	`contact` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`profile_photo_url` text,
	`profile_photo_metadata` text DEFAULT '{}' NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`name_en` text,
	`one_liner_en` text,
	`bio_en` text,
	`template_type_en` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `artists_legacy_id_unique` ON `artists` (`legacy_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `artists_slug_unique` ON `artists` (`slug`);--> statement-breakpoint
CREATE TABLE `member_profiles` (
	`id` text PRIMARY KEY NOT NULL,
	`display_name` text NOT NULL,
	`email` text NOT NULL,
	`phone_number` text,
	`birth_date` text,
	`real_name` text,
	`monthly_fee` integer,
	`bank_name` text,
	`account_number` text,
	`account_holder` text,
	`registration_status` text DEFAULT 'pending' NOT NULL,
	`is_active` integer DEFAULT false NOT NULL,
	`is_admin` integer DEFAULT false NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`approved_at` integer,
	`approved_by` text,
	`last_login_at` integer,
	`rejected_by` text,
	`suspension_reason` text,
	`suspension_until` integer,
	`is_suspended` integer DEFAULT false NOT NULL,
	`profile_completeness_score` integer DEFAULT 0 NOT NULL,
	`verification_status` text DEFAULT '{"email":false,"phone":false,"identity":false}' NOT NULL,
	`membership_type` text DEFAULT 'regular' NOT NULL,
	`engagement_score` integer DEFAULT 0 NOT NULL,
	`is_member` integer DEFAULT true NOT NULL,
	`artist_id` text,
	`is_artist` integer DEFAULT false NOT NULL,
	`artist_role` text DEFAULT 'owner' NOT NULL,
	`is_director` integer DEFAULT false NOT NULL,
	`director_title` text,
	`is_auditor` integer DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `member_profiles_email_idx` ON `member_profiles` (`email`);